import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillLinkedin, AiFillGithub, AiOutlineLink } from 'react-icons/ai'
import img1 from '../images/scentimental-cover.png';

export default function Home() {
  return (
    <>
      <Head>
        <title>Ryan's Portfolio</title>
        <meta name="description" content="Generated by ryan" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-space px-10'>
        <section className='h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='font-white'>Logo</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill />
              </li>
              <li><a href="#">Resume</a></li>
            </ul>
          </nav>
          <div>
            <h2>Ryan Ebanks</h2>
            <h3>Full-Stack Web Devloper/Software Engineer</h3>
            <p>
              I create modern yet simplistic applications to solve complex problems. Learn more about me below.
            </p>
            <div className='text-5xl flex gap-16 text-teal'>
              <AiFillLinkedin />
              <AiFillGithub />
            </div>
          </div>
          <div>
            <h1>About</h1>
            <p>
              Hi, I'm Ryan Ebanks and I'm a Full-Stack Web Developer in training.
              I have a bachelors degree in computer science which gives me a strong understanding
              of programming funadamentals such as data structures and object-oriented programming (OOPs).
              I'm orginally from Jamaica but now live in the USA which gives me a unique perspective in the way I think as
              well as my creative approach.
              I'm currently enrolled in the Rutgers Full-Stack Coding Bootcamp to harness my skills.
            </p>
          </div>
          <div>
            <h1>Portfolio</h1>
            <div className="max-w-sm rounded overflow-hidden shadow-lg">
              <div>
                <img src={img1} alt='Scentimental' />
              </div>
                <div className="px-6 py-4">
                  <div className="font-bold text-xl mb-2">Scentimental</div>
                  <p>
                    Scenti-mental is an ecommerce website that showcases their companies future products for the purpose of feedback before release. 
                  </p>
                </div>
                <div className='flex text-white'>
                <span>< AiOutlineLink /></span>
                  <a>Github</a>
                  <span>< AiOutlineLink /></span>
                  <a>App</a>
                </div>
                <div className="px-6 pt-4 pb-2">
                  <span className="inline-block bg-coral bg-opacity-50 rounded-full px-3 py-1 text-sm font-semibold text-red-300 mr-2 mb-2">JavaScript</span>
                  <span className="inline-block bg-coral bg-opacity-50 rounded-full px-3 py-1 text-sm font-semibold text-red-300 mr-2 mb-2">CSS</span>
                  <span className="inline-block bg-coral bg-opacity-50 rounded-full px-3 py-1 text-sm font-semibold text-red-300 mr-2 mb-2">Handlebars</span>
                  <span className="inline-block bg-coral bg-opacity-50 rounded-full px-3 py-1 text-sm font-semibold text-red-300 mr-2 mb-2">Express.js</span>
                </div>
            </div>
          </div>
        </section>

      </main>
    </>
  );
}
