import Head from 'next/head';
import Image from 'next/image';
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillLinkedin, AiFillGithub, AiOutlineLink } from 'react-icons/ai'
import { MdDownload } from 'react-icons/md'
import img1 from '../../public/images/scentimental-cover.png';

export default function Home() {
  return (
    <>
      <Head>
        <title>Ryan's Portfolio</title>
        <meta name="description" content="Generated by ryan" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-space px-10'>
        <section className='h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='font-white'>Logo</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill />
              </li>
              <li><a href="#">Resume</a></li>
            </ul>
          </nav>
          <div>
            <h2 className='text-5xl text-white'>Ryan Ebanks</h2>
            <h3 className='text-2xl text-white'>Full-Stack Web Devloper/Software Engineer</h3>
            <p className='text-lg text-white'>
              I create modern yet simplistic applications to solve complex problems. Learn more about me below.
            </p>
            <div className='text-5xl flex gap-16 text-teal'>
              <AiFillLinkedin />
              <AiFillGithub />
            </div>
          </div>
          <div>
            <h1 className='text-2xl text-white'>About</h1>
            <p className='text-base text-white'>
              Hi, I'm Ryan Ebanks and I'm a Full-Stack Web Developer in training.
              I have a bachelors degree in computer science which gives me a strong understanding
              of programming funadamentals such as data structures and object-oriented programming (OOPs).
              I'm orginally from Jamaica but now live in the USA which gives me a unique perspective in the way I think as
              well as my creative approach.
              I'm currently enrolled in the Rutgers Full-Stack Coding Bootcamp to harness my skills.
            </p>
          </div>
          <div>
            <h1 className='text-2xl text-white'>Portfolio</h1>
            <div className='flex content-center'>
              <div className='flex'>
                <Image src={img1} alt='Scentimental' width={400} className='rounded-lg' />
              </div>
              <div>
                <div className="px-6 py-4">
                  <div className=" text-white font-bold text-xl mb-2">Scentimental</div>
                  <p className='text-base text-white'>
                    Scenti-mental is an ecommerce website that showcases their companies future products for the purpose of feedback before release.
                  </p>
                </div>
                <div className='flex text-white'>
                  <span>< AiOutlineLink /></span>
                  <a>Github</a>
                  <span>< AiOutlineLink /></span>
                  <a>App</a>
                </div>
                <div className="px-6 pt-4 pb-2">
                  <span className="inline-block bg-coral bg-opacity-50 rounded-full px-3 py-1 text-sm font-semibold text-red-300 mr-2 mb-2">JavaScript</span>
                  <span className="inline-block bg-coral bg-opacity-50 rounded-full px-3 py-1 text-sm font-semibold text-red-300 mr-2 mb-2">CSS</span>
                  <span className="inline-block bg-coral bg-opacity-50 rounded-full px-3 py-1 text-sm font-semibold text-red-300 mr-2 mb-2">Handlebars</span>
                  <span className="inline-block bg-coral bg-opacity-50 rounded-full px-3 py-1 text-sm font-semibold text-red-300 mr-2 mb-2">Express.js</span>
                </div>
              </div>
            </div>
          </div>

          <div>
            <div>
              <h1 className='text-2xl text-white'>Resume</h1>
              <h1 className='text-base text-white'>Download here</h1>
              <button class="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded inline-flex items-center">
                < MdDownload />
                <span>Download</span>
              </button>
            </div>
            <h1 className='text-xl text-white'>Summary</h1>
            <p className='text-base text-white'>Front-end web developer with a background in Computer Science. Currently Training at the Rutgers coding boot camp to earn a certificate in full-stack web
              development. Innovative problem-solver passionate about developing apps; focused on mobile-first design and development. Strengths in creativity, teamwork,
              and building projects from ideation to execution.
            </p>

            <h2 className='text-xl text-white'>Technical Skills</h2>
            <p className='text-base text-white'><span className='font-bold'>Software/Platforms:</span></p>
            <p className='text-base text-white'><span className='font-bold'>Software Languages:</span></p>

            <h2 className='text-xl text-white'>Projects</h2>
            <p className='text-lg text-white'>Project #1 Template</p>
            <ul>
              <li className='text-base text-white'></li>
              <li className='text-base text-white'></li>
              <li className='text-base text-white'></li>
            </ul>
            <p className='text-lg text-white'>Project #2 Template</p>
            <ul>
              <li className='text-base text-white'></li>
              <li className='text-base text-white'></li>
              <li className='text-base text-white'></li>
            </ul>

            <h2 className='text-xl text-white'>Education</h2>
            <p className='text-base text-white'><span className='font-bold'>Program: </span>Rutgers Full-Stack Coding Bootcamp, Online</p>
            <p className='text-base text-white'>December 2022 - June 2023</p>
            <p className='text-base text-white'><span className='font-bold'>Degree: </span>University of Technology, Kingston, Jamaica</p>
            <p className='text-base text-white'>August 2017 - November 2021</p>
          </div>
        </section>

        <section>
          <div class="py-8 lg:py-16 px-4 mx-auto max-w-screen-md">
            <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-center text-gray-900 dark:text-white">Contact Us</h2>
            <p class="mb-8 lg:mb-16 font-light text-center text-gray-500 dark:text-gray-400 sm:text-xl">Got a technical issue? Want to send feedback about a beta feature? Need details about our Business plan? Let us know.</p>
            <form action="#" class="space-y-8">
              <div>
                <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Your email</label>
                <input type="email" id="email" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" placeholder="name@flowbite.com" required />
              </div>
              <div>
                <label for="subject" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Subject</label>
                <input type="text" id="subject" class="block p-3 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 shadow-sm focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" placeholder="Let us know how we can help you" required />
              </div>
              <div class="sm:col-span-2">
                <label for="message" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-400">Your message</label>
                <textarea id="message" rows="6" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg shadow-sm border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Leave a comment..."></textarea>
              </div>
              <button type="submit" class="py-3 px-5 text-sm font-medium text-center text-white rounded-lg bg-primary-700 sm:w-fit hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Send message</button>
            </form>
          </div>
        </section>
      </main>
    </>
  );
}
