import Head from 'next/head';
import Image from 'next/image';
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillLinkedin, AiFillGithub, AiOutlineLink } from 'react-icons/ai'
import img1 from '../../public/images/scentimental-cover.png';

export default function Home() {
  return (
    <>
      <Head>
        <title>Ryan's Portfolio</title>
        <meta name="description" content="Generated by ryan" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-space px-10'>
        <section className='h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='font-white'>Logo</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill />
              </li>
              <li><a href="#">Resume</a></li>
            </ul>
          </nav>
          <div>
            <h2>Ryan Ebanks</h2>
            <h3>Full-Stack Web Devloper/Software Engineer</h3>
            <p>
              I create modern yet simplistic applications to solve complex problems. Learn more about me below.
            </p>
            <div className='text-5xl flex gap-16 text-teal'>
              <AiFillLinkedin />
              <AiFillGithub />
            </div>
          </div>
          <div>
            <h1>About</h1>
            <p>
              Hi, I'm Ryan Ebanks and I'm a Full-Stack Web Developer in training.
              I have a bachelors degree in computer science which gives me a strong understanding
              of programming funadamentals such as data structures and object-oriented programming (OOPs).
              I'm orginally from Jamaica but now live in the USA which gives me a unique perspective in the way I think as
              well as my creative approach.
              I'm currently enrolled in the Rutgers Full-Stack Coding Bootcamp to harness my skills.
            </p>
          </div>
          <div>
            <h1>Portfolio</h1>
            <div className='flex content-center'>
              <div className='flex'>
                <Image src={img1} alt='Scentimental' width={400} className='rounded-lg' />
              </div>
              <div>
                <div className="px-6 py-4">
                  <div className="font-bold text-xl mb-2">Scentimental</div>
                  <p>
                    Scenti-mental is an ecommerce website that showcases their companies future products for the purpose of feedback before release.
                  </p>
                </div>
                <div className='flex text-white'>
                  <span>< AiOutlineLink /></span>
                  <a>Github</a>
                  <span>< AiOutlineLink /></span>
                  <a>App</a>
                </div>
                <div className="px-6 pt-4 pb-2">
                  <span className="inline-block bg-coral bg-opacity-50 rounded-full px-3 py-1 text-sm font-semibold text-red-300 mr-2 mb-2">JavaScript</span>
                  <span className="inline-block bg-coral bg-opacity-50 rounded-full px-3 py-1 text-sm font-semibold text-red-300 mr-2 mb-2">CSS</span>
                  <span className="inline-block bg-coral bg-opacity-50 rounded-full px-3 py-1 text-sm font-semibold text-red-300 mr-2 mb-2">Handlebars</span>
                  <span className="inline-block bg-coral bg-opacity-50 rounded-full px-3 py-1 text-sm font-semibold text-red-300 mr-2 mb-2">Express.js</span>
                </div>
              </div>
            </div>
          </div>

          <div>
            <h1>Resume</h1>
            <p>Front-end web developer with a background in Computer Science. Currently Training at the Rutgers coding boot camp to earn a certificate in full-stack web
              development. Innovative problem-solver passionate about developing apps; focused on mobile-first design and development. Strengths in creativity, teamwork,
              and building projects from ideation to execution.
            </p>
            <div class="flex flex-col">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full text-left text-sm font-light">
          <thead class="border-b font-medium dark:border-neutral-500">
            <tr>
              <th scope="col" class="px-6 py-4">#</th>
              <th scope="col" class="px-6 py-4">Languages</th>
              <th scope="col" class="px-6 py-4">Databases</th>
              <th scope="col" class="px-6 py-4">Tools & Frameworks</th>
            </tr>
          </thead>
          <tbody>
            <tr class="border-b dark:border-neutral-500">
              <td class="whitespace-nowrap px-6 py-4 font-medium">1</td>
              <td class="whitespace-nowrap px-6 py-4">HTML</td>
              <td class="whitespace-nowrap px-6 py-4">SQL</td>
              <td class="whitespace-nowrap px-6 py-4">Bootstrap</td>
            </tr>
            <tr class="border-b dark:border-neutral-500">
              <td class="whitespace-nowrap px-6 py-4 font-medium">2</td>
              <td class="whitespace-nowrap px-6 py-4">CSS3</td>
              <td class="whitespace-nowrap px-6 py-4">MongoDB</td>
              <td class="whitespace-nowrap px-6 py-4">Tailwindcss</td>
            </tr>
            <tr class="border-b dark:border-neutral-500">
              <td class="whitespace-nowrap px-6 py-4 font-medium">3</td>
              <td class="whitespace-nowrap px-6 py-4">JavaScript</td>
              <td class="whitespace-nowrap px-6 py-4">Wild</td>
              <td class="whitespace-nowrap px-6 py-4">Next.js</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
          </div>
        </section>

      </main>
    </>
  );
}
