import React from 'react';
import { MdDownload } from 'react-icons/md'

export function Resume() {
    return(
        <>
        <title>Ryan's Portfolio</title>
        <meta name="description" content="Generated by ryan" />
        <link rel="icon" href="/favicon.ico" />
        </>
    );
}

export default Resume;





<div>
            <div>
              <h1 className='text-2xl text-white'>Resume</h1>
              <h1 className='text-base text-white'>Download here</h1>
              <button class="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded inline-flex items-center">
                < MdDownload />
                <span>Download</span>
              </button>
            </div>
            <h1 className='text-xl text-white'>Summary</h1>
            <p className='text-base text-white'>Front-end web developer with a background in Computer Science. Currently Training at the Rutgers coding boot camp to earn a certificate in full-stack web
              development. Innovative problem-solver passionate about developing apps; focused on mobile-first design and development. Strengths in creativity, teamwork,
              and building projects from ideation to execution.
            </p>

            <h2 className='text-xl text-white'>Technical Skills</h2>
            <p className='text-base text-white'><span className='font-bold'>Software/Platforms:</span></p>
            <p className='text-base text-white'><span className='font-bold'>Software Languages:</span></p>

            <h2 className='text-xl text-white'>Projects</h2>
            <p className='text-lg text-white'>Project #1 Template</p>
            <ul>
              <li className='text-base text-white'></li>
              <li className='text-base text-white'></li>
              <li className='text-base text-white'></li>
            </ul>
            <p className='text-lg text-white'>Project #2 Template</p>
            <ul>
              <li className='text-base text-white'></li>
              <li className='text-base text-white'></li>
              <li className='text-base text-white'></li>
            </ul>

            <h2 className='text-xl text-white'>Education</h2>
            <p className='text-base text-white'><span className='font-bold'>Program: </span>Rutgers Full-Stack Coding Bootcamp, Online</p>
            <p className='text-base text-white'>December 2022 - June 2023</p>
            <p className='text-base text-white'><span className='font-bold'>Degree: </span>University of Technology, Kingston, Jamaica</p>
            <p className='text-base text-white'>August 2017 - November 2021</p>
          </div>